### ISSUE TITLE
Track more CRL warnings

### ISSUE THREAD

**Issue by ties** [ties/rpki-client-web#127]
```
rpki-client: rsync.example.org/repository/35e32bc1-a629-44b7-968d-86fb05fcf01d/0/B92878BC51346518F1FEB41640B62B344887ACF1.mft: unable to get certificate CRL
rpki-client: rpki.example.org/repository/DEFAULT/0f/331bcf-8e29-45bd-ab6c-f52b30e01820/1/BaYSj14pZXCsabRKG-pJ7HoYDvM.roa: referenced file supposed to be deleted
```

**Comment by job** [comment]
The `rpki-client: rpki.example.org/repository/DEFAULT/0f/331bcf-8e29-45bd-ab6c-f52b30e01820/1/BaYSj14pZXCsabRKG-pJ7HoYDvM.roa: referenced file supposed to be deleted` warning means that a RRDP `<withdraw .../>` was signaled from the RRDP server to the RRDP client; but there still are cryptographic valid references towards the supposedly-to-be-deleted file at hand. When this situation arises, `rpki-client` won't delete the file from its validated cache (thus ignoring the instruction from the RRDP server).

Under normal CA/publication operations, the CA would first revoke/delist a file, publish the new manifest, and perhaps in the same RRDP delta withdraw the revoked/delisted file item.

**Comment by ties** [comment]
The "referenced file supposed to be deleted" case is a nice catch. This is a gap in all the RPs that process files synchronously (instead of using garbage collection to find leftover files).
