### ISSUE TITLE
Listen on both IPv4 and IPv6

### ISSUE THREAD

**Issue by racompton** [ties/rpki-client-web#72]
Right now when specifying "host:" it's possible to populate "host: "::" to listen for IPv6 but there doesn't seem to be an option to listen for both IPv4 and IPv6 at the same time.

**Comment by ties** [comment]
I made a minimal change for this that works for me locally. Can you try it?

**Comment by racompton** [comment]
It's working!  Thanks!
```
sudo lsof -i -n -P | grep 8323
python3   181831   node_exporter    7u  IPv6 2555283      0t0  TCP *:8323 (LISTEN)
python3   181831   node_exporter    8u  IPv4 2555284      0t0  TCP *:8323 (LISTEN)

**Comment by ties** [comment]
Nice! This was the minimal change, glad that it works.

The alternative would be a list of places to listen + multiple sockets, using this native support was much easier.
